# Generated by Django 5.2.8 on 2025-11-25 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('prioridad', models.IntegerField(default=3)),
                ('etiquetas', models.CharField(blank=True, help_text='Escribe etiquetas separadas por comas, por ejemplo: estudio,python', max_length=255)),
                ('descripcion', models.TextField(blank=True)),
                ('completada', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
